### ISSUE TITLE
Improve front page (suggestions) 

### ISSUE THREAD

**Issue by sknico** [seedcase-project/seedcase-website#144]
(I am just trying to make an issue after out meeting yesterday. However, it is more a comment with my suggestions on how the front page could be impoved) 

Text: First section is about "funds, finding personnel, and allocating resources" but that is not our main concern/aim. E.g. start with the next section ("aims to ease the burden of building, managing, sharing, and accessing health data") insead. It should be clear for the reader/reseacher in the first paragraph why seedcase is a good idea ("installable software [...] to better connect data collectors, researchers, clinicians, and other stakeholders to created data") and why we chose the name "seedcase".

We mention that it is aimed at health data, but in the last section, diabetes is all of a sudden introduced. There is no need to include this here (better to move it to the section "About" where Steno+DD2 is mentioned). 

Small correction: "people with people with" 

Logo: Add the logo as a bigger picture (not just the small one in the corner) in order for the reader to actually see what it is. Explain the name/logo and maybe simplify/change color?

**Comment by signekb** [comment]
@lwjohnst86 This seems to be a bit outdated? Are there something from these comments that you would like to include on the landing page?
