### ISSUE TITLE
Discussion: repo naming as seedcase vs seedcase-project?

### ISSUE THREAD

**Issue by signekb** [seedcase-project/seedcase-website#150]
https://github.com/seedcase-project/seedcase-project/blob/56e3536e6b1bb543e82beea91d95f43fd53433ea/community/guide-entries/documentation-first/index.qmd#L82-L98

It's not entirely clear to me from the naming or description what the seedcase vs seedcase-project repo is :-)

Also: It seems there are more repos in the organisation (seedcase-registry and seedcase-theme) than on this list. Is this intentional or does this list need to be updated?

**Comment by lwjohnst86** [comment]
`seedcase-website` or `seedcase-home`.
