### ISSUE TITLE
Brainstorming: Ideas for slogan/catchphrase

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-website#234]
Something catchy to give the overall idea of what Seedcase is about. One idea:

1. "Growing data, spreading ideas"

**Comment by signekb** [comment]
Pre-meeting brainstorm:

**From data seeds to ...** (parenthesis bc we could omit "data"):
- "From (data) seeds to shared insights"
- "From (data) seeds to gardens of insights."

**Growing and harvesting**:
- "Growing data, cultivating knowledge."
- "Growing your data, harvesting shared knowledge"
- "Harvesting the power of data."
- "Harvesting the power of structured and shared data."
- "Cultivating a garden of data growth"

Something about **blooms** and **blossom**:
- "From data seeds to knowledge blooms."
- Where Data Seeds Blossom into Insights."

**Planting seeds**:
- "Planting the seeds to harvest insights" (too corporate?) 
- "Planting the seeds for growing data and share insights"
- "Planting the seeds for structured data growth and sharing"
- "Planting the seeds of open-source data structuring and sharing."

**Vague**:
- "Cultivating a garden of data."?
- "Growing data for shared success."?

**Comment by lwjohnst86** [comment]
Ooo really like some of those! Another one:

- "Cultivating data, spreading knowledge"

I think I want to avoid words like "insight", they sound way to cliché corporate sounding.

**Comment by signekb** [comment]
"Cultivating the seeds of knowledge"

**Comment by signekb** [comment]
"Reaping knowledge from the seeds of data"

**Comment by signekb** [comment]
"Sowing seeds, reaping rewards"

**Comment by signekb** [comment]
"From data seeds to blooms of knowledge"

**Comment by signekb** [comment]
"Where Data Seeds Blossom into Insights."

**Comment by signekb** [comment]
"Spreading the tools for data gardening"

**Comment by lwjohnst86** [comment]
Cultivating data, gleaning knowledge

Cultivating data, scattering knowledge

Planting data, growing knowledge

Propagating data, planting knowledge

Where data grows and knowledge spreads

Where data grows and knowledge blooms

We tentatively go with the last one above.
