### ISSUE TITLE
Brainstorm better landing page layout for main website

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/seedcase-website#239]
We would like a more visually pleasing landing page

**Comment by signekb** [comment]
@seedcase-project/developers I have made a mock-up in [Figma](https://www.figma.com/design/czeKwMxVLKPNQDX42eiTxq/Wireframes?node-id=1542-6068&t=Bm53FUFsgjkjGAxg-0). Check it out and please give some feedback.

**Comment by signekb** [comment]
We have gone through the layout/design during an update meeting and it seems that everyone is pleased with the design. 
I will close this issue and refer to #144 and #241 and an upcoming PR about implementing this layout.
