### ISSUE TITLE
Style improvements

### ISSUE THREAD

**Issue by martonvago** [seedcase-project/seedcase-website#241]
Just some comments about potential ways to improve the look of the main website, as per https://github.com/seedcase-project/team/issues/142. Some points probably overlap with other issues raised already, especially #239 and #144.

General:
* The logo and text in the top left corner could be styled in a more visually pleasing way, I’m thinking mainly about the colours and the proportions (related: https://github.com/seedcase-project/seedcase-theme/issues/22).

Landing page:
* We could consider moving up all the links in the grey boxes from the middle of the page to the header. There is already some duplication anyway, and to me it feels more natural to have a classic menu that stays there as you navigate around.
* Remove the floating “Our specific goals are:” up top.
* This way, some space would be freed up in the page body, and we could consider moving up as much content as we can. I’m just thinking that it would be nice if people visiting could see more of the project goals at first glance, without needing to scroll (which they might not).
* Related to the above, if the number of goals will stay ~4, we could maybe display them as cards/boxes with a prominent keyword/title and some explanatory lines underneath. This way, it might be easier to float more of them into the frame. Plus, it would also enable people to get a quick overview (and have their interest captured) without actually reading the text.

**Comment by signekb** [comment]
Nice, @martonvago! I'll take these comments into account in https://github.com/seedcase-project/seedcase-project/issues/239 and https://github.com/seedcase-project/seedcase-project/issues/144.

**Comment by lwjohnst86** [comment]
Nice suggestions!

**Comment by signekb** [comment]
Closed with #257
