### ISSUE TITLE
[feature-request]: Add aria-label to "brand logo" on websites to make them more accessible. 

### ISSUE THREAD

**Issue by signekb** [seedcase-project/seedcase-website#259]
### What feature would you like to request?

To increase accessibility of our websites, we should see if we can add an aria-label to the brand logos of our websites. This is the logo to the far left of the navbar that e.g., says "Seedcase Project", "Seedcase Design", or "Seedcase Sprout".

**Comment by lwjohnst86** [comment]
I believe we can solve this with the `logo-alt:` field that we can add in the `_quarto.yml` file. https://quarto.org/docs/websites/website-navigation.html#top-navigation

**Comment by signekb** [comment]
Ah, you're right! 🤩  Nice! I'll add it to #258 and rename the PR
